version: ~> 1.0
os: linux
dist: bionic
language: python
python: 3.6
install:
  - nvm install
  - npm ci
script:
  - pip install -r requirements.txt
  - ./manage.py migrate
  - ./manage.py loaddata fixtures.json
  - ./manage.py runserver &
  - mkdir pa11y/lighthouse
  - mkdir pa11y/screenshots
  - npm run test
  - node pa11y/report.js
  - mv pa11y/report.html pa11y/index.html
branches:
  except:
    - gh-pages
# deploy:
#   - provider: pages
#     strategy: git
#     skip_cleanup: true
#     local_dir: pa11y
#     token: "$PAGES_GITHUB_API_TOKEN"
#     on:
#       branch: main
notifications:
  email: false
env:
  global:
    # Permissions: public_repo
    # travis encrypt --org PAGES_GITHUB_API_TOKEN=<value>
    - secure: "axBDcfb7uFlYTH+4jnbghCNLo2PPWa879xv/9lBcMEx7/PChzOTdB1hxYugu1sslcv77DOr+zN6sqwYczEWqdOwaP4Wu0Lj2As6cagCpZIv/7JIrjaAxx+rq07a8kNHrJ1GeQzC212zW3Y+dkOQzuWJZdtk0QUJ0ZE0yu72uf055hQHkhn9Bui3Hrd9aydrLAfUn3Xo2eoOUIPlDO7UWusEZx5LSiQv/9w+Plnf0L+zwF5rJ+QQB9LFppv3o6X8OLoSdEX1hN68g5hSMz5ZmHSVWlkZQCIhk1+sumKiL34Fb7F+rVbdpdJcqSKI4pXMxgN8URsiNpfBDpy2vBvvld35SefSPhmcIw96yoLZfBXZhK3hIshl2futbTHJWT/7KyrPbg3cKM3fJYWlsGOqgUnvsIv6w5plYR/kBBfpDV7QXf8X/9SOBESaMppwok3I2FZTbxGMrS8zHi+jtgRkrh7VNKOrY0TJPWUEkimRxHzT+zyVJ2VeQjlYTA7fDKRPjRDhhGKldiHw5BNaHxap8saMHG0I0zSIE0kGcFY3bqv9+wVr7aIHbNo1zCQxY4FiHnGxfFoCOAeKV61Y2adeCGZWv04mAdOzHW5gmWVONNF3jblR5DOrOkS3uRr63cK6Z1xOqObq/aDKgIq8CJ41eUPV1fyiMuahSXygxpoaHT3o="
