# Generated by Django 5.2.dev20241204231626 on 2024-12-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_alter_releasetrack_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={
                "permissions": [("can_deliver_pizzas", "Can deliver pizzas")],
                "verbose_name": "Artist",
            },
        ),
    ]
