name: CI
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - id: pip-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pip-v2-${{ hashFiles('**/runtime.txt') }}-${{ hashFiles('**/requirements.txt') }}
      - if: steps.pip-cache.outputs.cache-hit != 'true'
        run: python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt
      - run: >
          if [ -z "${GITHUB_HEAD_REF}" ]; then
            source .venv/bin/activate && pip install -e git+https://github.com/django/django.git@main#egg=django
          else
            source .venv/bin/activate && pip install -e git+https://github.com/django/django.git@refs/pull/$GITHUB_HEAD_REF/head#egg=django
          fi
      - run: source .venv/bin/activate && ./manage.py makemigrations --check
      - run: source .venv/bin/activate && ./manage.py migrate --noinput
      - run: source .venv/bin/activate && ./manage.py runserver &
      - run: source .venv/bin/activate && ./manage.py collectstatic --noinput
      - run: ./snapshot/backup.sh || true
      - run: cp -R ./static/* ./django_admin_tests/django_admin_tests/v5.1/english/static
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: django_admin_tests/django_admin_tests
      - uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: django_admin_tests/django_admin_tests
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/deploy-pages@v4
  deploy_preview:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: snapshot
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: preview-${{ github.head_ref }}
          folder: django_admin_tests
          clean: true
