name: CI
on:
  push:
    branches-ignore:
      - "gh-pages"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - id: pip-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pip-v2-${{ hashFiles('**/runtime.txt') }}-${{ hashFiles('**/requirements.txt') }}
      - if: steps.pip-cache.outputs.cache-hit != 'true'
        run: python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt
      - run: source .venv/bin/activate && pip install -e git+https://github.com/django/django.git@main#egg=django
      - run: source .venv/bin/activate && ./manage.py makemigrations --check
      - run: source .venv/bin/activate && ./manage.py migrate --noinput
      - run: source .venv/bin/activate && ./manage.py runserver &
      - run: source .venv/bin/activate && ./manage.py collectstatic --noinput
      - run: ./snapshot/backup.sh
      - run: cp -R ./static/* ./django_admin_tests/django_admin_tests/v5.1/english/static
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: django_admin_tests/django_admin_tests
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/deploy-pages@v4
